
public class ExceptionDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		/*int numbers[] = {10,20,30,40,50};
		
		
		
		try {
			System.out.println(numbers[6]);
		} catch (Exception e) {
			System.out.println(e);
			//we can print the exception
			//we can return user friendly error mesages
			//we can write the logic to handel the exception 
		}
		
		System.out.println("next instructions");
		
		int x  =10;
		int y = 30;
		System.out.println("sum is "+x+y);*/
		
		
		/*String s1 = "test";
		
		
		try {
			System.out.println(s1.length());
		} catch (Exception e) {
			System.out.println("check the values in UI/ all are mandatory");
		}
		System.out.println("proceed");*/
		
		
		/*Thread t = new Thread(); // 
		t.setPriority(30);*/
		
		/*Object s1 = new String("hello");
		Integer i1 = (Integer)s1;*/
		
//		Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
//		at ExceptionDemo.main(ExceptionDemo.java:42)
//		
		
		
		//int x = 10/0;
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		//
		
		
		

	}

}

/*Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
at ExceptionDemo.main(ExceptionDemo.java:9)
*/


// Eception will occut at runtime
// abnormal termination 
// exception will occur beccause of invalid input
// we need to handle the exceptions and continue the flow
// we need to handle the exception and provide the user friendly error messages to
// the end user


